import UsersModel from "./users.service";import {updateUserQueue} from "../../Queue/userQueue";import {Request, Response} from "express";import {exception} from "../exception/exceprion";class UsersController {	async getAllUsers(req: Request, res: Response) {		try {			const allUsers = await UsersModel.getAll();			return res.json(allUsers);		} catch (e) {			return exception(res, e, 500)		}	}			async getOneUser(req: Request, res: Response) {		try {			const {id} = req.params;			const oneUserById = await UsersModel.getOneById(id);			return res.json(oneUserById);		} catch (e) {			return exception(res, e, 500)		}	}			async updateUser(req: Request, res: Response) {		try {			await updateUserQueue(req.body);			return res.json('User updated');		} catch (e) {			return exception(res, e, 500)		}	}			async deleteAllUsers(req: Request, res: Response) {		try {			const deleteAllUsers = await UsersModel.deleteAll();			return res.json(deleteAllUsers);		} catch (e) {			return exception(res, e, 500)		}	}			async deleteOneUser(req: Request, res: Response) {		try {			const deleteOneUser = await UsersModel.deleteOne(req.params.id);			return res.json(deleteOneUser);		} catch (e) {			return exception(res, e, 500)		}	}}export default new UsersController();